import json
from datetime import datetime

def run_single_prompt(prompt_text: str) -> dict:
    response = {
        "prompt": prompt_text,
        "response": "Mock response generated by the model.",
        "timestamp": datetime.utcnow().isoformat()
    }
    return response


if __name__ == "__main__":
    prompt = "Summarize the key risks in deploying an LLM system."
    result = run_single_prompt(prompt)

    print(json.dumps(result, indent=2))
